name: Ruby CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Gosu dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y libsdl2-dev libgl1-mesa-dev libfontconfig1-dev libopenal-dev libsndfile1-dev libmpg123-dev cmake xvfb pulseaudio
    - name: Install Gosu
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch master https://github.com/gosu/gosu
        cd gosu

        sed -i 's/^cmake_policy/# &/' cmake/GosuConfig.cmake
        mkdir -p build
        cd build
        cmake ..
        sed -i 's@set(CMAKE_INSTALL_PREFIX "/usr/local")@set(CMAKE_INSTALL_PREFIX "/usr")@g' cmake_install.cmake
        make
        sudo make install
        cd ..

        cd ../ffi-gosu
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

        sudo usermod -a -G audio $USER

        xvfb-run bundle exec rake
