name: Ruby CI

on:
  push:
    branches: [master]
  pull_request:

env:
  GOSU_GIT_BRANCH: master
  LTS_UBUNTU: ubuntu-18.04

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-18.04, ubuntu-latest, windows-latest]
        ruby-version: ['2.7', '3.0', '3.1']
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2


    - name: Install Gosu dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-18.04' || matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y build-essential libsdl2-dev libgl1-mesa-dev libgmp-dev libfontconfig1-dev cmake xvfb pulseaudio

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically

    - name: Add msbuild to PATH (Windows)
      if: matrix.platform == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.1

    - name: Fetch Gosu
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch ${{ env.GOSU_GIT_BRANCH }} https://github.com/gosu/gosu

    - name: Build and install Gosu (Linux)
      if: matrix.platform == 'ubuntu-18.04' || matrix.platform == 'ubuntu-latest'
      run: |
        echo $PWD
        cd ../gosu

        mkdir -p build
        cd build
        cmake -D CMAKE_INSTALL_PREFIX:PATH=/usr ..
        make
        sudo make install

    - name: Build Gosu with msbuild (Windows)
      if: matrix.platform == 'windows-latest'
      run: |
        echo $PWD

        cd ..
        cd gosu

        msbuild windows/Gosu.sln /property:Configuration=Release

    - name: Install dependencies
      run: gem install bundler && bundle install --jobs 4 --retry 3

    - name: Run tests (Linux)
      if: matrix.platform == 'ubuntu-18.04' || matrix.platform == 'ubuntu-latest'
      run: |
        sudo usermod -a -G audio $USER

        xvfb-run bundle exec rake

    - name: Run tests (Windows)
      if: matrix.platform == 'windows-latest'
      run: bundle exec rake
