name: Ruby CI

on: [push, pull_request]

env:
  GOSU_GIT_BRANCH: window-tweaks # switch to master after window-tweaks is merged

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install Gosu dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libgmp-dev libfontconfig1-dev cmake xvfb pulseaudio
    - name: Build and install Gosu
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch ${{ env.GOSU_GIT_BRANCH }} https://github.com/gosu/gosu
        cd gosu

        # sed -i 's/^cmake_policy/# &/' cmake/GosuConfig.cmake
        mkdir -p build
        cd build
        cmake ..
        sed -i 's@set(CMAKE_INSTALL_PREFIX "/usr/local")@set(CMAKE_INSTALL_PREFIX "/usr")@g' cmake_install.cmake
        make
        sudo make install
        cd ..

        cd ../ffi-gosu
    - name: Test with rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

        sudo usermod -a -G audio $USER

        xvfb-run bundle exec rake



  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Gosu with msbuild
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch ${{ env.GOSU_GIT_BRANCH }} https://github.com/gosu/gosu
        cd gosu

        msbuild windows/Gosu.sln /property:Configuration=Release
        cd ..

        cd ../ffi-gosu
    - name: Test with rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

        bundle exec rake
